//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by NonLinSystems.rc
//
#define IDR_NLSYSTYPE_SRVR_IP           4
#define IDR_NLSYSTYPE_SRVR_EMB          5
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_NLSYSTYPE                   129
#define IDD_PHASE_PLOT_PARAM            130
#define IDR_WINDOW_SIZE                 130
#define IDD_OPTIONS                     131
#define IDD_LOCATE_BIF_POINTS           132
#define IDD_PLOT_EQU_SURFACE            133
#define IDI_ICON1                       134
#define IDD_SHOW_BIF_POINTS             135
#define IDD_CALC_LYAP_EXP               136
#define IDD_SHOW_LYAP_EXP               137
#define IDD_INPUT_DIFFEQ_SYSTEM         139
#define IDD_PLOT_LYAP_EXP               140
#define IDD_TRAJECTORY_PLOT_PARAM       141
#define IDR_COMMANDS                    141
#define IDD_PLOT_SPECTRUM               143
#define IDD_CALC_EQU_SOLUTION           144
#define IDC_IDES_DIFFEQ_SYS             1000
#define IDC_PLOTPARAM_CHANGING_PAR      1000
#define IDC_IDES_START_VAL              1001
#define IDC_PAR_VALUES                  1001
#define IDC_PLOTPARAM_T1                1002
#define IDC_PLOTPARAM_T2                1003
#define IDC_PLOTPARAM_STEP              1004
#define IDC_IDES_IND_VAR                1005
#define IDC_PHASE_PLOTPARAM_SINGLE_PAR  1005
#define IDC_PLOTPARAM_START_VAL         1005
#define IDC_TPLOTPARAM_SINGLE_PAR       1006
#define IDC_PHASE_SCALE_Y_SAME          1006
#define IDC_TPLOTPARAM_MULTI_PARAM      1007
#define IDC_PHASE_PLOTPARAM_2D          1007
#define IDC_PHASE_PLOTPARAM_3D          1008
#define IDC_PHASE_PLOTPARAM_MULTI_PARAM2 1009
#define IDC_PLOTPARAM_TIME_VAR1         1010
#define IDC_PHASE_SCALE_Y_DIFFERENT     1010
#define IDC_PLOTPARAM_TIME_VAR2         1011
#define IDC_PHASE_PLOTPARAM_T1          1011
#define IDC_PLOTPARAM_TIME_VAR3         1012
#define IDC_PHASE_PLOTPARAM_T2          1012
#define IDC_PLOTPARAM_TIME_VAR4         1013
#define IDC_PHASE_PLOTPARAM_STEP        1013
#define IDC_PHASE_PLOTPARAM_X           1014
#define IDC_PHASE_PLOTPARAM_Y           1015
#define IDC_PHASE_PLOTPARAM_Z           1016
#define IDC_PHASE_PLOTPARAM_CHANGING_PAR 1017
#define IDC_PHASE_PAR_VALUES            1018
#define IDC_PLOTPARAM_LEGEND_VAR1       1019
#define IDC_PLOTPARAM_LEGEND_VAR2       1020
#define IDC_PLOTPARAM_LEGEND_VAR3       1021
#define IDC_PLOTPARAM_LEGEND_VAR4       1022
#define IDC_SCALE_Y_SAME                1023
#define IDC_SCALE_Y_DIFFERENT           1024
#define IDC_IDES_PARAM                  1025
#define IDC_PLOTPARAM_SAVE_NUM          1025
#define IDC_PHASE_PLOTPARAM_SAVE_NUM    1026
#define IDC_PLOTPARAM_PARAM_VAL         1026
#define IDC_PLOTPARAM_EPS               1027
#define IDC_PHASE_PLOTPARAM_EPS         1028
#define IDC_OPTIONS_NEW_WINDOW          1029
#define IDC_OPTIONS_SAME_WINDOW         1030
#define IDC_PHASE_PLOTPARAM_PLOT_T1     1032
#define IDC_PHASE_PLOTPARAM_PLOT_T2     1033
#define IDC_PLOTPARAM_PLOT_T1           1034
#define IDC_PLOTPARAM_PLOT_T2           1035
#define IDC_LOC_BIF_VAR_START           1036
#define IDC_LOC_BIF_PAR_START           1037
#define IDC_LOC_BIF_EIGEN_START         1038
#define IDC_LOC_BIF_SNB                 1041
#define IDC_LOC_BIF_HOPF                1042
#define IDC_PLOT_EQU_X                  1043
#define IDC_PLOT_EQU_Y                  1044
#define IDC_PLOT_EQU_Z                  1045
#define IDC_PLOT_EQU_RANGE1_FROM        1046
#define IDC_PLOT_EQU_RANGE1_TO          1047
#define IDC_PLOT_EQU_RANGE2_FROM        1048
#define IDC_PLOT_EQU_RANGE2_TO          1049
#define IDC_PLOT_EQU_2D                 1050
#define IDC_PLOT_EQU_3D                 1051
#define IDC_LOC_BIF_RANDOMIZE_EIGEN     1052
#define IDC_LIST_SNB_POINTS             1056
#define IDC_LIST_HOPF_POINTS            1057
#define IDC_SNB_EIGENVAL                1058
#define IDC_HOPF_EIGENVAL               1059
#define IDC_LOC_BIF_SEARCH_NUM          1060
#define IDC_LOC_BIF_EQU_SOL_STATE_VAR   1061
#define IDC_calc_LYAP_MIN_STEPSIZE      1063
#define IDC_calc_LYAP_MAX_ITER_NUM      1064
#define IDC_CALC_LYAP_EPS               1065
#define IDC_CALC_LYAP_T                 1066
#define IDC_CALC_LYAP_VAR_START         1067
#define IDC_CALC_LYAP_PAR_VAL           1068
#define IDC_SHOW_LYAP_LIST_VAL          1069
#define IDC_SHOW_LYAP_EXP_VAL           1070
#define IDC_LOC_BIF_AUTOMATIC           1071
#define IDC_PLOT_LYAP_FIXED_VAL         1073
#define IDC_PLOT_LYAP_CHANGE_PAR        1074
#define IDC_PLOT_LYAP_CONNECT           1075
#define IDC_PLOT_LYAP_MARK              1076
#define IDC_PLOT_LYAP_X1                1077
#define IDC_PLOT_LYAP_X2                1078
#define IDC_PLOT_LYAP_STEP              1079
#define IDC_PLOT_LYAP_USE_ALREADY_CALC  1080
#define IDC_PLOT_LYAP_CALC_ALL          1081
#define IDC_LOC_BIF_P1                  1082
#define IDC_LOC_BIF_P2                  1083
#define IDC_PLOT_LYAP_MAX_ITER_NUM      1084
#define IDC_PLOT_LYAP_MIN_STEPSIZE      1085
#define IDC_PLOT_LYAP_EPS               1086
#define IDC_PLOT_LYAP_T                 1087
#define IDC_PHASE_PLOTPARAM_START_VAL   1088
#define IDC_PHASE_PLOTPARAM_PARAM_VAL   1089
#define IDC_TRAJECTORY_PLOT_TITLE       1090
#define IDC_PHASE_PLOT_TITLE            1091
#define IDC_PLOTSPECTRUM_VAR1           1092
#define IDC_PLOTSPECTRUM_VAR2           1093
#define IDC_PLOTSPECTRUM_VAR3           1094
#define IDC_PLOTSPECTRUM_VAR4           1095
#define IDC_PLOTSPECTRUM_LEGEND_VAR1    1096
#define IDC_PLOTSPECTRUM_LEGEND_VAR2    1097
#define IDC_PLOTSPECTRUM_LEGEND_VAR3    1098
#define IDC_PLOTSPECTRUM_LEGEND_VAR4    1099
#define IDC_OPTIONS_STEPMIN             1100
#define IDC_OPTIONS_EPS                 1101
#define IDC_PLOT_EQU_SHOW_BIF           1102
#define IDC_OPTIONS_USE_COLOR           1103
#define IDC_EQU_SOL_PAR_VAL             1105
#define IDC_EQU_SOL_SYS_VAR             1106
#define IDC_EQU_SOL_PAR_VAL_FOUND       1111
#define IDC_EQU_SOL_SYS_VAR_FOUND       1112
#define IDC_EQU_SOL_EIGENVAL            1113
#define IDC_EQU_SOL_CALCULATE           1115
#define IDC_EQU_SOL_MAX_ITER            1116
#define IDC_EQU_SOL_EPS                 1117
#define IDC_PLOT_LYAP_EPS_REL           1118
#define IDC_PLOT_LYAP_EPS_ABS           1119
#define IDC_CALC_LYAP_EPS_REL           1120
#define IDC_CALC_LYAP_EPS_ABS           1121
#define ID_CANCEL_EDIT_SRVR             32769
#define ID_EDIT_DIFF_EQUATIONS          32771
#define ID_PLOT_TRAJECTORY              32772
#define ID_PLOT_PHASE_CURVE             32773
#define ID_PLOT_EQUIL_SOLUTIONS         32774
#define ID_PLOT_BIFUR_SURFACE           32775
#define ID_PLOT_BIFUR_DIAGRAM           32776
#define ID_PLOT_X_LEFT                  32785
#define ID_PLOT_X_RIGHT                 32786
#define ID_PLOT_Y_UP                    32787
#define ID_PLOT_Y_DOWN                  32788
#define ID_PLOT_X_EXPAND                32789
#define ID_PLOT_Y_EXPAND_WINDOW         32790
#define ID_PLOT_X_CONDENSE              32792
#define ID_PLOT_Y_CONDENSE_WINDOW       32794
#define ID_PLOT_GET_CLOSER              32795
#define ID_PLOT_GET_FARTHER             32796
#define ID_ROTATE_LEFT                  32799
#define ID_ROTATE_RIGHT                 32800
#define ID_ROTATE_UP                    32804
#define ID_ROTATE_DOWN                  32805
#define ID_RESET_MUL                    32806
#define ID_PLOT_EXPAND_BOTH             32807
#define ID_PLOT_CONDENSE_BOTH           32808
#define ID_PLOT_LIAPUNOV_EXP            32809
#define ID_PLOT_FOURIER                 32812
#define ID_ANAL_LOCATE_BIF              32813
#define ID_PLOT_SET_LEGEND_POS          32814
#define ID_MOVE_CENTER_UP               32815
#define ID_MOVE_CENTER_RIGHT            32817
#define ID_MOVE_CENTER_CLOSER           32819
#define ID_MOVE_CENTER_DOWN             32821
#define ID_MOVE_CENTER_LEFT             32822
#define ID_MOVE_CENTER_FURTHER          32823
#define ID_VIEW_BIF_POINTS              32824
#define ID_ANAL_CALC_LYAP_EXP           32825
#define ID_ANAL_CALC_EQU_SOL            32826
#define ID_VIEW_LYAP_EXP                32827
#define ID_OPTIONS_SET_OPTIONS          32828
#define ID_OPTIONS_SHOW_LEGEND          32829
#define ID_FOURIER_DRAW                 32830
#define ID_TRAJECTORY_PLOT              32831
#define ID_PHASE_DIAGRAM_PLOT           32832
#define ID_LOC_BIF                      32833
#define ID_CALC_LYAP_EXP                32834
#define ID_OPTIONS_SHOW_BIF_IN_EQU_SURF 32835
#define ID_OPTIONS_SET_BIF_LEGEND_POS   32836
#define IDS_ERR_NOT_VAR_NAME            61191
#define IDS_ERR_NOT_SYS_VAR             61192
#define IDS_ERR_NO_VAR_ENTERED          61193
#define IDS_FIRST_EQU_SURF_MUST_BE_PAR  61194
#define IDS_NO_EQV_SOL_IN_THIS_INTERVAL 61195
#define IDS_DIDNT_FIND_BIF_POINT        61196
#define IDS_FOURIER_PLOT_ONLY_FOR_TRAJECTORIES 61197
#define IDS_BIF_POINTS_FIND_ONLY_FOR_ONE_PAR_SYS 61198
#define IDS_WRONG_PAR_FOR_BIF_POINTS_LOC 61199
#define IDS_WRONG_PAR_FOR_LYAP_EXP_CALC 61200
#define IDS_WRONG_PLOT_TIME             61201
#define IDS_NOT_SYS_NOT_PAR             61204
#define IDS_STRING61205                 61205
#define IDS_FINISHED_WITH_BIF_POINTS_CALC 61206
#define IDS_SHOW_LEGEND                 61207
#define IDS_HIDE_LEGEND                 61208
#define IDS_NO_LYAP_EXP_CALC            61209
#define IDS_FINISHED_WITH_LYAP_EXP_CALC 61210
#define IDS_WRONG_INIT_COND_OR_PAR_VAL  61211
#define IDS_CHG_PAR_NOT_GIVEN           61212
#define IDS_EMPTY_PARAMETER_LIST        61213
#define IDS_VAR1_FOR_MULTI_PAR          61214
#define IDS_ALREADY_CALCULATING_FOR_THIS_WINDOW 61216
#define IDS_COULDNT_FIND_EQU_SOL        61217
#define IDS_ERR_NOT_GIVEN_VAR_NAME      61218

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32837
#define _APS_NEXT_CONTROL_VALUE         1122
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
